name: Run Tests

on:
  pull_request:
    branches: [ main, staging ]
  push:
    branches: [ staging ]  # Only run on staging pushes, not main
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-services:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: anagram_game_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies - Game Server
      working-directory: services/game-server
      run: npm ci

    - name: Install dependencies - Web Dashboard
      working-directory: services/web-dashboard
      run: npm ci

    - name: Install dependencies - Link Generator
      working-directory: services/link-generator
      run: npm ci

    - name: Set up test database
      env:
        DB_HOST: localhost
        DB_USER: postgres
        DB_PASSWORD: test_password
        DB_NAME: anagram_game_test
      run: |
        # Install PostgreSQL client
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        
        # Create test schema
        PGPASSWORD=test_password psql -h localhost -U postgres -d anagram_game_test -f services/game-server/shared/database/schema.sql

    - name: Run service health tests
      env:
        DB_HOST: localhost
        DB_USER: postgres
        DB_PASSWORD: test_password
        DB_NAME: anagram_game_test
        NODE_ENV: test
      run: |
        # Test database connection
        cd services/game-server
        node -e "
          const { testConnection } = require('./shared/database/connection');
          testConnection().then(() => {
            console.log('✅ Database connection test passed');
            process.exit(0);
          }).catch(err => {
            console.error('❌ Database connection test failed:', err);
            process.exit(1);
          });
        "

    # Docker builds and iOS tests moved to separate workflow for production releases